# .github/workflows/conventional-pr.yml

name: conventional-pr
on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - edited
      - synchronize
jobs:
  label:
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: label
        uses: action-runner/conventional-labeler@1.3.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  outdater:
    runs-on: ubuntu-latest
    name: Dependencies outdater
    steps:
      - name: Dependencies Outdater
        uses: action-runner/dependencies-outdater@1.2.5
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

